import assert from 'node:assert/strict';
import fs from 'node:fs/promises';

const directory = new URL('../libraries/messages/', import.meta.url);
const entries = JSON.parse(await fs.readFile(new URL('opcodes.json', directory), 'utf8'));
const names = new Set(), values = new Set();
for (const entry of entries) {
  assert.match(entry.name, /^OP_[A-Z][A-Z0-9_]*$/);
  assert.match(entry.opcode, /^0x[0-9a-f]{8}$/);
  assert.ok(entry.evidence?.trim(), entry.name + ': missing naming evidence');
  assert.ok(!names.has(entry.name), 'Duplicate opcode name: ' + entry.name);
  assert.ok(!values.has(entry.opcode), 'Ambiguous opcode entry: ' + entry.opcode);
  names.add(entry.name);
  values.add(entry.opcode);
}
assert.deepEqual(entries.map(x => x.name), [...names].sort((a, b) => a.localeCompare(b)), 'Keep opcode names sorted');

for (const extension of ['fc', 'tolk']) {
  const comment = extension === 'fc' ? ';;' : '//';
  const contents = `${comment} decompiled by @fiscaldev\n` +
    `${comment} Generated by tools/opcodes.mjs. Naming evidence: opcodes.json and ../../READABILITY.md.\n` +
    entries.map(({name, opcode}) => `const ${extension === 'fc' ? 'int ' : ''}${name} = ${opcode}${extension === 'fc' ? ';' : ''}`).join('\n') + '\n';
  const file = new URL('opcodes.' + extension, directory);
  if (process.argv.includes('--write')) await fs.writeFile(file, contents);
  else assert.equal(await fs.readFile(file, 'utf8'), contents, `opcodes.${extension} differs from its reviewed catalog; run npm run opcodes:generate`);
}
console.log(`${entries.length} named opcodes: FunC/Tolk catalogs consistent`);
